file_format: '1.1'

log_level: warn

resource:
  detection/development:
    detectors:
      - composer:
      - container:
      - host:
      - process:

meter_provider:
  readers:
    - pull:
        exporter:
          prometheus/development:
            host: 0.0.0.0
            scope_info_enabled: false
